### ISSUE TITLE
How do I add a room.onPlayerChat? I just couldn't run

### ISSUE THREAD

**Issue by SaNaTKaR04** [FeliMattei/Haxball-Headless-Host#2]
I couldn't run the spamfilter code

**Comment by FeliMattei** [comment]
With the code I passed you, add it to _room.onPlayerChat_

spammerFilter (player, message);
    if (filter (message)) return false;

**Comment by SaNaTKaR04** [comment]
https://prnt.sc/sr1jt9

**Comment by SaNaTKaR04** [comment]
Thank you for everything, finally can you give me the code to kick those who don't move in the game?

**Comment by FeliMattei** [comment]
No problem, any questions create an issue!

I never made a specific code on that, but you could check [this function](https://github.com/haxball/haxball-issues/wiki/Headless-Host#onplayeractivity).

This function detects who does not move, maybe you could think something with it

**Comment by SaNaTKaR04** [comment]
I need help
Can't you do anything about my room sniper hitting or kicking the ball?

**Comment by FeliMattei** [comment]
something like that?

**Comment by SaNaTKaR04** [comment]
How can i make a chat filter

**Comment by FeliMattei** [comment]
```
function filter(message){
    message = message.toLowerCase();
    message = message.replace(/\s/g, '');
    message = message.replace(/\./g,' ')
    if(message.includes("word1") ||message.includes("wordn")){
        return true;
    }else {
        return false;
    }
}

room.onPlayerChat = function(player, message) {
          if(filter(message)) return false;
}
```
you can add words: `||message.includes ("word")` inside the IF

**Comment by SaNaTKaR04** [comment]
Can't you do anything related to afk? Please
